<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <ReleaseVersion>0.0.1</ReleaseVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.1.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.9" />
    <PackageReference Include="Moq" Version="4.16.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IdentityApi\IdentityApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Data\" />
    <None Remove="Mockings\" />
    <None Remove="Ordering\" />
    <None Remove="Microsoft.EntityFrameworkCore.InMemory" />
    <None Remove="Moq" />
    <None Remove="Account\" />
    <None Remove="Auth\" />
    <None Remove="Identifiers\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Mockings\" />
    <Folder Include="Ordering\" />
    <Folder Include="Account\" />
    <Folder Include="Auth\" />
    <Folder Include="Identifiers\" />
  </ItemGroup>
</Project>
