name: IdentityApi

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  helmVersion: 3.7.0
  HELM_EXPERIMENTAL_OCI: 1
  tag: '$(Build.BuildId)'
  dockerfilePath: '**/Dockerfile'

steps:
 - task: Docker@2
   displayName: Build and publish docker image
   inputs:
    containerRegistry: ""
    repository: ""
    command: buildAndPush
    Dockerfile: $(dockerfilePath)
    tags: |
      $(tag)