name: IdentityApi

# trigger:
# - main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd0ee37c6-ad7b-407e-b5ff-b7bf63093093'
  imageRepository: 'identityapi'
  containerRegistry: 'tmsolutioncr.azurecr.io'
  dockerfilePath: '**/Dockerfile'  
  helmVersion: 3.7.0
  HELM_EXPERIMENTAL_OCI: 1
  helmChart: './identityapi-chart'
  tag: $(build.SourceVersion)

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildImage
  displayName: Build and push docker image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:            
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:          
        command: buildAndPush    
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: BuildHelmChart
  displayName: Build and push helm chart
  jobs:
    - job: Build      
      steps:
        - task: HelmInstaller@1
          displayName: 'install helm'
          inputs:
            helmVersionToInstall: $(helmVersion)
        - bash: |
            # run helm lint
            helm lint $(helmChart)
          failOnStderr: true
          displayName: 'helm lint'
        - bash: |
            helm package \
            --app-version $(tag) \
            $(helmChart)
          failOnStderr: true
          displayName: 'helm package'
        - task: PublishBuildArtifacts@1
          displayName: Helm package          
        - bash: |
           #still experimental in Helm v3
           export HELM_EXPERIMENTAL_OCI=1

           # Helm needs to login to ACR
           helm registry login $(containerRegistry) 

        #    # Save the Helm chart locally - version tag comes from chart version
        #    # A local save is required before you can push the chart to ACR
        #    chartVersion=`helm chart save charts/template $(containerRegistry)/helm/$(imageRepository) | grep version | awk -F ': ' '{print $2}'`

        #    # Push the chart
        #    # Note: if a chart with the same version already exists, it will be overwritten
        #    #       this might not be the behavior you want
        #    helm chart push $(containerRegistry)/helm/$(imageRepository):$chartVersion

        #    # save the Helm chart version and image tag to a JSON file to publish as an artifact
        #    echo $(jq -n --arg chartVersion "$chartVersion" --arg imgVersion "$(imageTag)" '{chartVersion: $chartVersion, imgVersion: $imgVersion}') > $(build.artifactStagingDirectory)/variables.json

          failOnStderr: true
          name: helmPush
          displayName: 'helm chart push'
        
        # - publish: $(build.artifactStagingDirectory)
        #   artifact: build-artifact
# - stage: DeployService
#   displayName: Deploy service to k8s
#   jobs:
#     - job: 
#       steps:
#         - task: HelmInstaller@1
#           inputs:
#             helmVersionToInstall: $(helmVersion)
        