name: IdentityApi

# trigger:
# - main

resources:
  repositories:
    - repository: templates
      type: github
      name: itsbibeksaini/pipeline-templates
      endpoint: github.com_itsbibeksaini

pr: none

variables:  
  imageRepository: 'identityapi'
  helmChart: './identityapi-chart'  
  valueFile: './identityapi-chart/values.yaml'
  imagePullSecret: 'tmsolutioncr6942264c-auth'
  helmVersion: 3.7.0
  containerRegistry: tmsolutioncr.azurecr.io
  vmImageName: ubuntu-latest

stages:
- stage: BuildImage
  displayName: Build and push docker image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:         
    - template: build-image.yml@templates
      parameters:
        tag: $(Build.SourceBranchName)_$(Build.SourceVersion)
        imageRepository: $(imageRepository)