// <auto-generated />
using System;
using IdentityApi.Services.SQLServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentityApi.Migrations
{
    [DbContext(typeof(IdentityStore))]
    partial class IdentityStoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityApi.DataModels.Credential", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PROFILE_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("SALT")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SECRET_HASH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID");

                    b.HasIndex("PROFILE_ID");

                    b.ToTable("CREDENTIALS");
                });

            modelBuilder.Entity("IdentityApi.DataModels.Profile", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATED_BY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATED_ON")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EMAIL_VERIFIED")
                        .HasColumnType("bit");

                    b.Property<string>("LANGUAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LOCKED")
                        .HasColumnType("bit");

                    b.Property<int>("LOGIN_ATTEMPTS")
                        .HasColumnType("int");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MODIFIED_ON")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PROFILE");
                });

            modelBuilder.Entity("IdentityApi.DataModels.RefreshToken", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("BROWSER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEVICE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GENERATED_ON")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPv4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LIFE_SPAN")
                        .HasColumnType("int");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROFILE_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("REFRESHED_ON")
                        .HasColumnType("datetime2");

                    b.Property<string>("SHA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.Property<string>("TOKEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("REFRESH_TOKENS");
                });

            modelBuilder.Entity("IdentityApi.DataModels.Credential", b =>
                {
                    b.HasOne("IdentityApi.DataModels.Profile", "PROFILE")
                        .WithMany()
                        .HasForeignKey("PROFILE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PROFILE");
                });
#pragma warning restore 612, 618
        }
    }
}
