apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: identityapi
spec:
  routes:
    - match:
        http:
          pathPrefix: /auth
      destination:
        service: identityapi
