apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: identityapi
spec:
  destination:
    name: identityapi
  sources:
    - name: tmsolution-ingress
      action: allow
    - name: tmsolution-gateway
      action: allow
