name: Identity API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    uses: the-experimentals/github-workflows/.github/workflows/dotnet-build.yml@main
    with:
      SOLUTION_FILE: ./IdentityApi.sln
      PROJECT_FILE: ./IdentityApi/IdentityApi.csproj
      TEST_PROJECT_FILE: ./IdentityApiTest/IdentityApiTest.csproj
