name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: itsbibeksaini/github-workflows/.github/workflows/dotnet-build.yml@main
    with:
      SOLUTION_FILE: ./IdentityApi.sln
      PROJECT_FILE: ./IdentityApi/IdentityApi.csproj
      TEST_PROJECT_FILE: ./IdentityApiTest/IdentityApiTest.csproj
      PROJECT_NAME: IdentityApi
  
  image:
    uses: itsbibeksaini/github-workflows/.github/workflows/docker-build.yml@main
    needs: build
    with:
      DOCKERFILE: "IdentityApi/Dockerfile"
      IMAGE_NAME: "identityapi"
      PROJECT_NAME: IdentityApi
  
  push:
    uses: itsbibeksaini/github-workflows/.github/workflows/docker-push-image.yml@main
    needs: image
    with:
      IMAGE_NAME: "identityapi"
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
  deploy:
    uses: itsbibeksaini/github-workflows/.github/workflows/helm-deploy.yml@main
    needs: push
    with:
      IMAGE_NAME: "identityapi"
      HELM_CHARTS: "./identityapi-chart"
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
