name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: itsbibeksaini/github-actions-workflows/.github/workflows/dotnet-build.yml@main
    with:
      SOLUTION_FILE: ./IdentityApi.sln
      PROJECT_FILE: ./IdentityApi/IdentityApi.csproj
      TEST_PROJECT_FILE: ./IdentityApiTest/IdentityApiTest.csproj
  image:
    uses: itsbibeksaini/github-actions-workflows/.github/workflows/docker-build.yml@main
    with:
      DOCKERFILE: "IdentityApi/Dockerfile"
      IMAGE_NAME: "identityapi"
      TAG: $(echo $GITHUB_SHA | head -c7)
#     - uses: actions/checkout@v3
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v2
#       with:
#         dotnet-version: 6.0.x
#     - name: Restore dependencies
#       run: dotnet restore ./IdentityApi.sln
#     - name: Build
#       run: dotnet build ./IdentityApi/IdentityApi.csproj --no-restore
#     - name: Test
#       run: dotnet test ./IdentityApiTest/IdentityApiTest.csproj --verbosity normal
